// Runs one SQL file generated by `npm run db:generate` against DATABASE_URL.
// Usage: npm run db:apply -- drizzle/0001_add_something.sql
import fs from "node:fs";
import { neon } from "@neondatabase/serverless";

const file = process.argv[2];
const url = process.env.DATABASE_URL;

if (!file || !fs.existsSync(file)) {
  console.error("Usage: npm run db:apply -- drizzle/<file>.sql");
  process.exit(1);
}
if (!url) {
  console.error("DATABASE_URL is not set (put it in .env).");
  process.exit(1);
}

const statements = fs
  .readFileSync(file, "utf8")
  .split("--> statement-breakpoint")
  .map((s) => s.trim())
  .filter(Boolean);

// Safety net for the shared database: only this project's objects may be touched.
function touchesOtherApps(statement: string): boolean {
  if (/\bDROP\s+(TYPE|SEQUENCE|SCHEMA|EXTENSION)\b/i.test(statement)) return true;
  const names = [...statement.matchAll(/\b(?:TABLE|INDEX|ON)\s+(?:IF\s+(?:NOT\s+)?EXISTS\s+)?(?:"public"\.)?"([^"]+)"/gi)].map((m) => m[1]);
  return names.some((name) => !name.startsWith("360dep_"));
}

const forbidden = statements.find(touchesOtherApps);
if (forbidden) {
  console.error("Refusing to run a statement that could affect other apps' objects:\n" + forbidden);
  process.exit(1);
}

const sql = neon(url);
await sql.transaction(statements.map((s) => sql.query(s)));
console.log(`✓ Applied ${statements.length} statement(s) from ${file}`);
